### PR TITLE
S3 support

### PR DESCRIPTION
**Pull request by arvkonstantin**

### CODE REVIEW

**Comment by striezel** [comment]
Thank you for the pull request. :tada:

I am not sure I completely understand what this change is supposed to achieve. As far as I understand it, it tries to upload the generated image file to an AWS S3 bucket, if the HTTP header `x-s3-enabled` is set to `true`. But I do not really understand why this should be done. Do you have a particular use case for this?

**Comment by arvkonstantin** [comment]
Yes, you're right. Use cases:
1) For example, you have a kubernetes cluster. You can't rely on the file system because you probably don't know which instance of the service will respond to you.
2) For example, you use a serverless service from Google or Amazon. After a successful response to the request, the container instance will be destroyed, along with the picture inside. 
3) Cloud storage allows you to configure file management more flexibly: lifetime, volume limits. In your case, this is not controlled in any way.

You can reject the merge if you think that this tool does not need cloud storage, but if you decide that it will not be superfluous, you can tell me what to fix in the code, because I did it in a hurry.

Thanks!

**Comment by striezel** [comment]
To be completely frank, I am not really happy with that approach for several reasons.
- Adding S3 support feels like adding a lot of bloat. The number of packages installed by NPM changes from 65 to 165, and the `package-lock.json` (if it were updated with all the dependencies for the AWS stuff) would grow from currently 478 lines to 1591 lines, more than three times the size. I am not willing to take in all this dependencies just for supporting one particular cloud provider.
- If I accept S3 support, then - naturally - somebody else might want support for Google Cloud Platform or for Microsoft Azure or for basically any other cloud provider that is out there. This would mean more dependencies, more bloat, and more distraction from the basic task that this tool is achieving: to render images with the help of ECharts.
- With both previous points it does not feel that this change solves a problem but potentially opens up more problems. However, that is by no means your fault. It is the fault of a decision I made when the tool was created - the decision to store generated images on the server side.

It is now clear that this decision was problematic and has to change, so I am currently working on some changes to provide the generated image directly in the HTTP response message to the rendering request. See https://github.com/striezel/echarts-node-export-server/commit/6eaa8fb7a51d5f33957735e159a1f75cbb0a159a (and following commits on the branch [direct-response](https://github.com/striezel/echarts-node-export-server/tree/direct-response) to get an idea what this will look like. I still need to run a few tests, but I guess that will be part of the next major release, 5.0.0. (Estimated release is within the next 24 hours.)

Once this change is on master, the client gets the image directly and can then decide what to do with it. That way, people who do not use S3 do not need to pull in the AWS dependencies on the server, and those who do use S3 can perform uploads to S3 buckets on the client side, if it is needed. The same holds true for any other cloud provider. So people only need to pull in the dependencies they are actually using on the client side instead of creating dependencies for every possible cloud on the server side. I believe that this is an acceptable solution to all three use cases you described.

**Comment by striezel** [comment]
[Version 5.0.0](https://github.com/striezel/echarts-node-export-server/releases/tag/v5.0.0) is out. You might want to try this new version.

I am closing this pull request, because as stated earlier I believe that the new release addresses the given use cases in a better way than adding support for cloud providers directly to the server. However, feel free to open another pull request for other improvements that you find a useful addition to the tool.

**Pull request closed without merging**
